customhost = "empoyee-db.cbz07m9yn5kn.ap-south-1.rds.amazonaws.com"
customuser = "admin"
custompass = "RDSEmployee"
customdb = "empoyee-db"
custombucket = "addemployee-bucket"
customregion = "ap-south-1"
